### ISSUE TITLE
transform .rdata into mysql

### ISSUE THREAD

**Issue by fifth** [fifth/gene-ontology-database#2]

**Comment by lytze** [comment]
从 Pombase 下载的源数据已经在文件夹里了, 是一个类似 `.csv` 格式的文件, 你可以试试怎样变换一下, 或者你看看网站上有没有提供直接下载成 sql 的方式.
如果需要的话, 我可以把 `.rdata` 里已经做过整理的表格导出成 `.csv` 应该比较容易转换吧, 需要的话告诉我一下

**Comment by fifth** [comment]
嗯，我大致看了一遍了，我主要是在思考我们这个应用到底是直接使用R来完成别的语言辅助；还是说按照老师说的那样用php然后mysql搭建站点然后R只占处理的这部分

**Comment by lytze** [comment]
明天课上聊一聊呗~

**Comment by lytze** [comment]
R 也是有 SQL 接口的, 如果老师要求必须要用 SQL, 也是有 Solution 的

**Comment by fifth** [comment]
解决方案肯定是有的毕竟现在R这么流行。我想转换成SQL是必须的因为这门课要求就是用MYSQL来做数据库，如果完全脱离也不太好（老师同意那另说）。而且使用rdata的话某种意义上数据库了哈哈
明天上课再聊好了，我这边也有好多不懂的地方要问你，顺便向老师打探一下底限的要求
